version: '3'
services:
  db:
    image: postgis/postgis:11-3.0-alpine
  server:
    build: .
    image: peakresponse/peak-server
    command: bash -l -c "npm start"
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:3000
    depends_on:
      - db
    volumes:
      - ./public/uploads:/opt/node/app/public/uploads
