version: '2'
services:
  db:
    image: postgis/postgis:11-3.0-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
      - 1080:1080
      - 1025:1025
  server:
    build: .
    image: natriage/nat-server
    command: bash -l -c "bin/init; nf start -j Procfile.dev"
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    environment:
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_USERNAME=none
      - SMTP_PASSWORD=none
      - PORT=3000
      - DATABASE_URL=postgres://postgres@db/app
      - DATABASE_TEST_URL=postgres://postgres@db/app_test
    ports:
      - 3000:3000
      - 3001:3001
      - 8080:8080
    depends_on:
      - db
